version: '3.8'
networks:
  mc_app:
    external: false
    name: mc_app

services:
  db:
    container_name: mc_db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: Naren
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: manage_contacts
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"

  web:
    build:
      context: .
      args:
        - HTTP_PROXY
        - HTTPS_PROXY
        - NO_PROXY
    container_name: mc_web
    restart: always
    environment:
      NODE_ENV: ${NODE_ENV}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      DB_PORT: ${DB_PORT}
      DB_HOST: ${DB_HOST}
      PORT: ${PORT}
    ports:
      - "80:80"